export {
  RichTextEditorCompound as RichTextEditor,
  type RichTextEditorProps,
  RTEToolbar,
  type RTEToolbarProps,
  RTEContent,
  type RTEContentProps,
  RTEBold,
  RTEItalic,
  RTEUnderline,
  RTEStrike,
  RTECode,
  RTECodeBlock,
  RTEHeadingSelect,
  type RTEHeadingSelectProps,
  RTEBulletedList,
  RTENumberedList,
  RTEIndent,
  RTEOutdent,
  RTEBlockquote,
  RTELink,
  RTEUndo,
  RTERedo,
  RTESeparator,
  type RTESeparatorProps,
  RTELinkDialog,
  type RTELinkDialogProps,
  RTEImageDialog,
  type RTEImageDialogProps,
  RTEFooter,
  type RTEFooterProps,
  RTECharacterCount,
  type RTECharacterCountProps,
  RTEHelpText,
  type RTEHelpTextProps,
} from './rich-text-editor';

export {
  useRichTextEditorContext,
  type RichTextEditorContextValue,
} from './rich-text-editor-context';

// Re-export core adapter types so consumers don't need @compa11y/core directly
export type {
  RTEAdapter,
  RTEAdapterFactory,
  RTEFormat,
  RTEMark,
  RTEBlock,
  RTESelectionState,
  RTEFeatures,
  RTECommands,
  RTECapabilities,
  RTEMountOptions,
  RTEValue,
} from '@compa11y/core';
